import { Figtree } from 'next/font/google';

import ToasterProvider from '@/providers/ToasterProvider';
import SupabaseProvider from '@/providers/SupabaseProvider';
import UserProvider from '@/providers/UserProvider';
import ModalProvider from '@/providers/ModalProvider';
import getSongsByUserId from '@/actions/getSongsByUserId';
import Sidebar from '@/components/Sidebar';
import Player from '@/components/Player';

import './globals.css';

const font = Figtree({ subsets: ['latin'] });

export const metadata = {
  title: 'EchoVibes | Frontier',
  description: 'Music mp3 web app Generated by Frontier Development',
};

export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const userSongs = await getSongsByUserId();

  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterProvider />
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider />

            <Sidebar songs={userSongs}>{children}</Sidebar>

            <Player />
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
